Override pthread_mutex_init() to force PTHREAD_PRIO_NONE
rr-debugger/rr pull request #2752
Opened 2020-11-26 07:13 UTC by mdavidsaver

When `PTHREAD_PRIO_INHERIT` is set, `pthread_mutex_init()` from glibc performs a test `futex()` call to probe for OS support.  This fails with RR.  Workaround by forcing `PTHREAD_PRIO_NONE`.

Attempts to address #2750

2020-11-26 09:18 UTC, rocallahan requested changes
Looks good. I assume the test passes for you...

2020-11-26 09:18 UTC, rocallahan commented on src/preload/overrides.c
> +    return ret;
We put {} around this statement

2020-11-26 17:06 UTC, mdavidsaver commented
```
$ ctest -R pthread
Test project /home/mdavidsaver/source/rr
    Start  390: pthread_pi_mutex
1/8 Test  #390: pthread_pi_mutex ........................   Passed    0.09 sec
    Start  391: pthread_pi_mutex-no-syscallbuf
2/8 Test  #391: pthread_pi_mutex-no-syscallbuf ..........   Passed    0.08 sec
    Start  392: pthread_rwlocks
3/8 Test  #392: pthread_rwlocks .........................   Passed    0.10 sec
    Start  393: pthread_rwlocks-no-syscallbuf
4/8 Test  #393: pthread_rwlocks-no-syscallbuf ...........   Passed    0.09 sec
    Start  422: pthread_condvar_locking
5/8 Test  #422: pthread_condvar_locking .................   Passed    0.09 sec
    Start  423: pthread_condvar_locking-no-syscallbuf
6/8 Test  #423: pthread_condvar_locking-no-syscallbuf ...   Passed    0.09 sec
    Start 1104: check_patched_pthread
7/8 Test #1104: check_patched_pthread ...................   Passed    1.64 sec
    Start 1105: check_patched_pthread-no-syscallbuf
8/8 Test #1105: check_patched_pthread-no-syscallbuf .....   Passed    1.65 sec
...
$ ctest -R mutex
Test project /home/mdavidsaver/source/rr
    Start 390: pthread_pi_mutex
1/4 Test #390: pthread_pi_mutex .................   Passed    0.09 sec
    Start 391: pthread_pi_mutex-no-syscallbuf
2/4 Test #391: pthread_pi_mutex-no-syscallbuf ...   Passed    0.08 sec
    Start 926: mutex_pi_stress
3/4 Test #926: mutex_pi_stress ..................   Passed    8.12 sec
    Start 927: mutex_pi_stress-no-syscallbuf
4/4 Test #927: mutex_pi_stress-no-syscallbuf ....   Passed    7.37 sec
```

2020-11-27 01:59 UTC, merged

2020-11-27 01:59 UTC, rocallahan commented
Thanks!

2020-12-01 05:47 UTC, Keno commented
This patch causes the robust_futex test to fail for me (EINVAL during the `pthread_mutex_lock(mutex)` in the thread).

2020-12-01 06:48 UTC, mdavidsaver commented
oops.  @rocallahan do you need another PR for this change?

```diff
diff --git a/src/preload/overrides.c b/src/preload/overrides.c
index bbc4189d..78c5141f 100644
--- a/src/preload/overrides.c
+++ b/src/preload/overrides.c
@@ -48,7 +48,7 @@ int pthread_mutex_init(pthread_mutex_t* mutex,
    * still returns the requested protocol.
    * So we copy the attribute and force PTHREAD_PRIO_NONE.
    */
-  memcpy(&realattr, &attr, sizeof(realattr));
+  memcpy(&realattr, attr, sizeof(realattr));
   ret = pthread_mutexattr_setprotocol(&realattr, PTHREAD_PRIO_NONE);
   if (ret) {
     return ret
```

2020-12-01 09:33 UTC, rocallahan commented
Landed as a48d578784425c648d1e86674afd0d54b98366da

2020-12-01 09:51 UTC, rocallahan commented
Also needed e8ac3786406f0a2025eabd76718c0b0b245e628c