Forward SIGKILL to detached children (fix #3016)
rr-debugger/rr pull request #3019
Opened 2021-12-22 10:21 UTC by Keno

When we detach a child, we keep around the zombie (or more accurately,
we keep it in PTRACE_EVENT_EXIT state) of the original process to
prevent the kernel from re-using it's pid and to enable
basic wait4 processing using the original child's tid to make the
detach of the child as transparent as possible to any traced parent.
However so far, we did not handle signals targeting the original tid.
That's not really a big problem, because ptrace zombies don't really have
signal handling. As an exception to this however, a SIGKILL will advance
the ptrace zombie out of PTRACE_EVENT_EXIT state and into a proper zombie
state, which our `wait_any` listener will reap. This reaping then
confuses our later handling of this process leading to #3016. Fix that
by keeping track of the detached proxies and forwarding any received
SIGKILLs after which our regular processing will take care of notifying
the parent appropriately.

Fixes #3016.

2021-12-22 11:08 UTC, rocallahan requested changes

2021-12-22 11:08 UTC, rocallahan commented on src/Scheduler.cc
> +    // probably beacause the parent or some other task tried to SIGKILL it
`because`

2021-12-29 08:45 UTC, GitMensch commented
If the typo in the comment is the only reason that this isn't merged - can we merge it in as is and just fix it?

2021-12-29 15:28 UTC, Keno commented
I fixed the typo. It'd just slipped my mind :)

2021-12-29 20:27 UTC, merged