Spelling
rr-debugger/rr pull request #3449
Opened 2023-02-27 07:33 UTC by jsoref

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/rr/actions/runs/4276402800#summary-11608769511

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/rr/actions/runs/4276403008#summary-11608769777

---

- [ ] Did you run the rr test suite (including your new tests, if any), and pass all the tests?  `make -C $objdir check`.  Unfortunately, rr doesn't have automated infrastructure that can run the tests yet, so developers have to run them locally.

  -- Unfortunately, I'm running on macOS, and I generally rely on CI...I tried running checks in GitHub and they appeared to take >6hrs...

- [x] Does your PR apply cleanly on top of upstream/master HEAD?  It's dangerous to have someone else sort out your merge conflicts, so just don't do it.  Best of all is to have a PR *rebased* on top of upstream/master HEAD, so that the merge is simply a fast-forward.

- [x] If your PR includes multiple changesets, do they all (i) build cleanly in sequence;
- [ ]  (ii) pass all tests in sequence?  This is important for bisecting over commit history.

- [x] If your PR is large or includes many changesets, would it have been possible to break the changes into a series of smaller PRs?  For example, it's hard to review a big patch that, say, fixes whitespace errors in a file along with a one-line, important, bug fix.  It's much easier to review one PR that fixes whitespace (which can just be skimmed), and then review another PR that makes the one-line bug fix (which would be scrutinized more).  This approach is also better for the patch author in that it usually allows the work to land faster, and reduces the burden of continually un-bit-rotting large, trivial, changes.

  -- It's possible to split almost any of these commits into their own PRs, but I'd rather let the project decide.

- [x] Did you check your code is formatted correctly? It's easiest to run `scripts/reformat.sh` on each commit.

2023-02-27 07:37 UTC, jsoref commented on src/RecordTask.h
> -   * Linux requires the invariant that that all members of a thread group
sometimes doubled `that` is intentional. It didn't appear to be in this repository

2023-02-27 07:37 UTC, jsoref commented on src/test/x86/ptrace_tls.c
> +  /* Next we're going to verify that these are actually reflected into the LDT
`in to`/`into` changes have been controversial. I'm happy to drop this or any other change

2023-02-27 08:32 UTC, rocallahan commented
Hello Timeless!

2023-02-27 08:59 UTC, rocallahan requested changes

2023-02-27 08:59 UTC, rocallahan commented on third-party/brotli/enc/hash_composite_inc.h
> +  /* TODO: Initialize of the hashers is deferred to Prepare (and params
Don't patch anything in third-party. These sources are imported unchanged from upstream sources so any local changes just make our lives difficult.

2023-02-28 06:04 UTC, khuey commented
I don't have any strong opinions about the patches but I do want these commits to be squashed when this is merged.

2023-02-28 10:02 UTC, rocallahan commented
Yes, please squash now.

2023-02-28 13:46 UTC, jsoref commented
Do you have any preference about the commit message?

GitHub can let repository owners squash during merge.

(Otherwise, I'll be able to squash in a few hours.)

2023-02-28 15:08 UTC, khuey commented
Yeah we can squash it on merge.

2023-03-01 09:32 UTC, merged

2023-03-01 09:32 UTC, rocallahan commented
Thanks!