Add rr commands to remove and move traces
rr-debugger/rr pull request #3566
Opened 2023-07-19 19:56 UTC by vinhill

As discussed in #1415, this pull request implements `rr rm` and `rr mv` commands to manage traces.

See #3558 for a similar pull request using `std::filesystem` that was closed because that library caused build errors.

2023-07-24 11:45 UTC, rocallahan requested changes

2023-07-24 11:45 UTC, rocallahan commented on src/RmCommand.cc
> +  if (ret)
{} around if body

2023-07-24 11:45 UTC, rocallahan commented on src/TraceStream.h
> +extern std::string latest_trace_symlink();
These don't actually need `extern` do they? let's remove it

2023-07-24 11:45 UTC, rocallahan commented on src/util.cc
> +    if (log_error) fprintf(stderr, "\nrr: Trace name cannot be empty\n\n");
These all need {} around the if body, and `fprintf` on its own line

2023-07-24 19:04 UTC, vinhill commented on src/MvCommand.cc
> +  if (from_path == to_path) {
I check that `to_path` doesn't exist and `real_path` requires an existing path.
But given `from_path` exists,  I guess checking `from_path==to_path` is irrelevant.

2023-07-24 20:29 UTC, vinhill commented on src/util.h
> +bool is_valid_trace_name(const std::string& entry, bool log_error=false);
Yeah, that function isn't pretty. If I understand you correctly, `is_valid_trace_name(entry, TraceNameCheck::verbose)` also doesn't seem best to me. Is a `string*` out param okay?

2023-07-26 20:59 UTC, rocallahan requested changes
The rest looks fine.

2023-07-26 20:59 UTC, rocallahan commented on src/MvCommand.cc
> +  if (int ret = rename(from_path.c_str(), to_path.c_str())) {
Remove the declaration of `ret` here, it's causing a build error on CI.

2023-07-29 11:30 UTC, merged

2023-07-29 11:30 UTC, rocallahan commented
Thanks!