AVX512 Support
rr-debugger/rr pull request #3776
Opened 2024-07-03 15:15 UTC by theIDinside

This PR introduces AVX512 support in replays.

CMake Changes:
Added the AVX512F_SUPPORT flag to CMake. Set by checking
if system supports AVX512F. If it doesn't it will not build (and therefore run) any of the AVX512 tests

Added the target descriptions. Assumed that PKRU support also implies AVX512 support as I could find no information that said otherwise.

Added gdb_avx512 test - sets 3 ZMM registers and reads them back in a gdb session of a replay to verify the contents.

We place mask registers K0-K7 after ZMM31H internally, because this simplifies the logic that parses the XSAVE area. The target description we provide, takes this into account (and also places them last) so they come after the ZMM registers in the 'g' packet. GDB doesn't care so long as we do what we say in the target desc

Changed test harness util.sh to also export TESTNAME variable as we may (this one test do at least) want to query from the python script what mode we are running in (64-bit/32-bit). See gdb_avx512.py for further info.

Not tested or developed for:
- Being able to write to / alter AVX512 registers during replay/diversion.

2024-07-07 17:20 UTC, khuey commented
I'll look at this in detail this week.

The assumption that AVX-512 implies PKRU is not necessarily correct because these two features can be controlled independently by the kernel. So it's possible to have a system with AVX-512 available but PKRU unavailable even if the silicon supports both. I do wonder if we could start pretending that certain things are available when they're not (e.g. for reads returning default register values and for writes returning errors) to avoid a combinatorial explosion in the number of target description XML files we need to ship. We're already up to 20 files. Any thoughts @rocallahan?

2024-07-08 15:52 UTC, theIDinside commented
> I'll look at this in detail this week.
> 
> The assumption that AVX-512 implies PKRU is not necessarily correct because these two features can be controlled independently by the kernel. So it's possible to have a system with AVX-512 available but PKRU unavailable even if the silicon supports both. I do wonder if we could start pretending that certain things are available when they're not (e.g. for reads returning default register values and for writes returning errors) to avoid a combinatorial explosion in the number of target description XML files we need to ship. We're already up to 20 files. Any thoughts @rocallahan?

GDB has a way to signal "could not read", which means, we could potentially do something like this:

Have a "one description to rule them all" (ish) kind of thing, and then just have RR splat 'x' in all the right places. Sure, it will mean that when reporting registers an architecture doesn't even have, we are doing the extra work of filling (N*regWidth + ...) bytes of 'x' into the g-packet, so that has to be taken into consideration.

At least this could be done for the PKRU (and potentially similar CPU features) feature, as it doesn't involve all that much unnecessary data.

2024-07-08 16:07 UTC, theIDinside commented
I guess we can assume the presence of AVX & AVX2 too, since these are very common features these days anyhow.

2024-07-08 20:46 UTC, rocallahan commented
> We're already up to 20 files.

We could dynamically assemble the top-level XML file. I.e. given the base CPU type (aarch64, i386, amd64) and some set of optional features (a subset of `avx`, `pkeys`, soon `avx512`), we report a register description file name of `<cpu>-<feature1>-...<featureN>-linux.xml` but don't actually ship all those files with rr. Instead when the client requests  file of that form, we can send dynamically generated contents with the `xi:include`s corresponding to the feature tags in the file name.

2024-07-08 20:47 UTC, rocallahan commented
> > We're already up to 20 files.
> 
> We could dynamically assemble the top-level XML file. I.e. given the base CPU type (aarch64, i386, amd64) and some set of optional features (a subset of `avx`, `pkeys`, soon `avx512`), we report a register description file name of `<cpu>-<feature1>-...<featureN>-linux.xml` but don't actually ship all those files with rr. Instead when the client requests file of that form, we can send dynamically generated contents with the `xi:include`s corresponding to the feature tags in the file name.

2024-07-09 12:15 UTC, theIDinside commented
> > We're already up to 20 files.
> 
> We could dynamically assemble the top-level XML file. I.e. given the base CPU type (aarch64, i386, amd64) and some set of optional features (a subset of `avx`, `pkeys`, soon `avx512`), we report a register description file name of `<cpu>-<feature1>-...<featureN>-linux.xml` but don't actually ship all those files with rr. Instead when the client requests a file of that form, we can send dynamically generated contents with the `xi:include`s corresponding to the feature tags in the file name.

Great idea. I think GDB does something similar under the hood. I can add this feature to this PR, or in a later PR, if we're all in agreement. What say you @khuey || @rocallahan ?

The feature would basically involve:

- Do the feature checking we already do
- Change `target_description_name` to `target_feature_set` to instead return a `Set<CPUFeature /* the GdbServerConnection::enum */>` as these are what determines what features are represented in the final `target.xml`
- Using the returned set, hand-serialize a `target.xml` with all the `<xi:include href="feature.xml">` 
- send over the wire

2024-07-09 17:19 UTC, rocallahan commented
> I think GDB does something similar under the hood. I can add this feature to this PR, or in a later PR, if we're all in agreement.

I think we should do it before this PR.

2024-07-10 08:08 UTC, theIDinside commented
> > I think GDB does something similar under the hood. I can add this feature to this PR, or in a later PR, if we're all in agreement.
> 
> I think we should do it before this PR.

Ok, can I wrap it up in the same PR or create a separate PR for it?

2024-07-10 09:10 UTC, rocallahan commented
Separate PR I think, thanks

2025-02-20 12:57 UTC, khuey commented on src/GdbServerConnection.cc
> +        cpu_features |= GdbServerConnection::CPU_AVX | GdbServerConnection::CPU_AVX512 | GdbServerConnection::CPU_PKU;
No, because these can be independently disabled (like we tell Pernosco customers to do, for instance).

2025-02-21 21:11 UTC, theIDinside commented on CMakeLists.txt
> +try_compile(AVX512F_SUPPORT ${CMAKE_SOURCE_DIR} ${CMAKE_SOURCE_DIR}/src/test/gdb_avx512.c CMAKE_FLAGS -DCOMPILE_DEFINITIONS=-march=native)
I currently do not have (non-trivial) access to a machine without avx512f, but I figured using try_compile, we won't get build errors on machines without avx512f support. Maybe this is not needed? (`AVX512F_SUPPORT` is later checked, when adding the test, so if the platform can't succesfully compile it, it's not going to be tested either).

2025-02-21 21:12 UTC, khuey commented on CMakeLists.txt
> +try_compile(AVX512F_SUPPORT ${CMAKE_SOURCE_DIR} ${CMAKE_SOURCE_DIR}/src/test/gdb_avx512.c CMAKE_FLAGS -DCOMPILE_DEFINITIONS=-march=native)
If you have a Linux machine you can get a machine without AVX-512 by putting clearcpuid=304 in your kernel boot parameters.

2025-02-21 22:25 UTC, theIDinside commented on src/GdbServerConnection.cc
> +        cpu_features |= GdbServerConnection::CPU_AVX | GdbServerConnection::CPU_AVX512 | GdbServerConnection::CPU_PKU;
> In general nothing implies anything because these feature sets can be independently disabled. We tell Pernosco customers to disable AVX-512 all the time ...

I'll fix this assumption (I think you mentiond this months ago as well).

2025-02-21 22:35 UTC, theIDinside commented on src/ExtraRegisters.cc
> +  DEBUG_ASSERT(selector >= 0 && selector <= 5 && "GdbServerRegister enum values has been changed.");
Sure, I can change it to something like

```cpp
static bool reg_is_avx2_or_512(GdbServerRegister reg, RegData& out) noexcept {
  if (reg < DREG_64_YMM0H || reg > DREG_64_K7) {
    return false;
  }

  uint64_t index = UINT64_MAX;
  if (reg >= DREG_64_YMM0H && reg < DREG_64_XMM16) {
    index = 0;
  } else if ( reg>= DREG_64_XMM16 && reg <DREG_64_YMM16H) {
    index = 1;
  } else if (reg >= DREG_64_YMM16H && reg < DREG_64_ZMM0H) {
    index = 2;
  } else if (reg >= DREG_64_ZMM0H && reg < DREG_64_ZMM16H) {
    index = 3;
  } else if (reg >= DREG_64_ZMM16H && reg < DREG_64_K0) {
    index = 4;
  } else if (reg >= DREG_64_K0 && reg < (DREG_64_K7+1)) {
    index = 5;
  }

  if (index == UINT64_MAX) {
    return false;
  }

  const auto cfg = register_config_lookup_table[index];
  out.xsave_feature_bit = cfg.feature;
  out.size = cfg.size;

  // only YMM16-31 and ZMM16-31 have a base offset (16 and 32 respectively)
  const auto base_offset = ((index == YMM16_31) || (index == ZMM16_31)) ? cfg.size : 0;
  out.offset = cfg.register_offset(reg, base_offset);
  return true;
}
```

I think I did the selector approach to cut down on the branching, this is probably easier to follow though.

2025-02-22 12:08 UTC, theIDinside commented on CMakeLists.txt
> +try_compile(AVX512F_SUPPORT ${CMAKE_SOURCE_DIR} ${CMAKE_SOURCE_DIR}/src/test/gdb_avx512.c CMAKE_FLAGS -DCOMPILE_DEFINITIONS=-march=native)
Thanks! I'll do that

2025-02-23 04:23 UTC, rocallahan commented on CMakeLists.txt
> +try_compile(AVX512F_SUPPORT ${CMAKE_SOURCE_DIR} ${CMAKE_SOURCE_DIR}/src/test/gdb_avx512.c CMAKE_FLAGS -DCOMPILE_DEFINITIONS=-march=native)
Aren't we mixing up compiler support with AVX512 support here?
Whether gcc/clang can compile the test should depend on compiler version, not whether your CPU supports AVX512. I think you should be able to build the test successfully even if your CPU doesn't have AVX512.

2025-02-23 19:40 UTC, rocallahan requested changes

2025-02-23 19:40 UTC, rocallahan commented on src/ExtraRegisters.cc
> +  const auto cfg = register_config_lookup_table[index];
It would be a little cleaner if `RegisterConfig` stored the upper bound as well as the base; then you could just search the table to find the right entry instead of computing the index with that big if chain.

2025-02-23 19:40 UTC, rocallahan commented on CMakeLists.txt
> +      set_source_files_properties("${CMAKE_CURRENT_BINARY_DIR}/32/${test}.c" PROPERTIES COMPILE_FLAGS "-m32 ${RR_TEST_FLAGS} -g3 -mavx512f")
Do you really need `-mavx512f`? What happens if you remove that (and make this a regular test), and remove the `defined(__AVX512F__)` code in the test? I think it will probably just work? That test only uses AVX512 via inline assembly which I don't think requires `-mavx512f`.

2025-02-23 20:48 UTC, theIDinside commented on src/ExtraRegisters.cc
> +  const auto cfg = register_config_lookup_table[index];
right, I get what you mean, I'll do that!

2025-02-23 20:56 UTC, theIDinside commented on src/ExtraRegisters.cc
> +  const auto cfg = register_config_lookup_table[index];
I'm also going to rename it to `RegisterDescriptor` as I believe this better describes what it's doing.

2025-02-23 21:29 UTC, theIDinside commented on CMakeLists.txt
> +      set_source_files_properties("${CMAKE_CURRENT_BINARY_DIR}/32/${test}.c" PROPERTIES COMPILE_FLAGS "-m32 ${RR_TEST_FLAGS} -g3 -mavx512f")
> Do you really need `-mavx512f`? What happens if you remove that (and make this a regular test), and remove the `defined(__AVX512F__)` code in the test? I think it will probably just work? That test only uses AVX512 via inline assembly which I don't think requires `-mavx512f`.

There's an interesting error that occurs when I remove the `-mavx512f` flag (and do not use `-march=native`): 

```
../src/test/x86/gdb_avx512.c:42:5: error: the register ‘zmm30’ cannot be clobbered in ‘asm’ for the current target
   42 |     asm volatile (
```

However, if I change the clobbered register to be something like `zmm9` and `zmm10` it _does_ compile without the flags, which means I can still test the contents of the registers is ok, but not all the way up to zmm31

2025-02-23 22:23 UTC, theIDinside commented on CMakeLists.txt
> +      set_source_files_properties("${CMAKE_CURRENT_BINARY_DIR}/32/${test}.c" PROPERTIES COMPILE_FLAGS "-m32 ${RR_TEST_FLAGS} -g3 -mavx512f")
It worked just fine to remove it, had to change what registers get clobbered though, but that's probably just me being unfamiliar with inline assembly, because I have no idea why that had to happen.

2025-02-24 07:37 UTC, rocallahan requested changes

2025-02-24 07:37 UTC, rocallahan commented on src/ExtraRegisters.cc
> +  GdbServerRegister end_exclusive;
If you make it `end_inclusive` that simplifies the table definiition and the code is almost the same.

2025-02-24 07:37 UTC, rocallahan commented on src/GdbServer.cc
> +  // TODO: Do we really need to allocate this every time for a reg request?q
Remove this. I think it's fine.

2025-02-24 07:37 UTC, rocallahan commented on src/GdbServer.cc
> +    for (auto reg = start; reg < end; reg = GdbServerRegister(reg + 1)) {
Make this `end_inclusive` and it will simplify the code.

2025-02-24 07:37 UTC, rocallahan commented on src/test/x86/gdb_avx512.c
> +main(void)
`int main(void)` in one line

2025-02-24 07:37 UTC, rocallahan commented on src/test/x86/gdb_avx512.c
> +#include <immintrin.h>
I think you can remove this.

2025-02-24 09:38 UTC, theIDinside commented
I'll rebase when we complete the review.

2025-02-24 10:18 UTC, merged

2025-02-24 10:18 UTC, rocallahan commented
I squashed it. Thanks!!!

2025-03-17 14:13 UTC, sidkshatriya commented
@theIDinside  
Hey I noticed something which I think probably should be remedied. 

In case you obtained (or obtained and then modified) the following xml files from [gdb](https://sourceware.org/gdb/current/)  sources:   
- `64bit-avx512.xml`
- `32bit-avx512.xml`
(these files were added to `rr` master in https://github.com/rr-debugger/rr/commit/2c1d0b237782116bfc7cd1fd8920685262cb1fa9 in this PR i.e. #3776 )

(see latest version for `64bit-avx512.xml` at https://sourceware.org/git/?p=binutils-gdb.git;a=blob_plain;f=gdb/features/i386/64bit-avx512.xml;hb=refs/heads/master )
(see latest version for `32bit-avx512.xml` here https://sourceware.org/git/?p=binutils-gdb.git;a=blob_plain;f=gdb/features/i386/32bit-avx512.xml;hb=refs/heads/master )

I'm noticing the Copyright and License header missing for the two XMLs in the `rr` git repository (compared to the `gdb` sources). Should this header (see below) be restored/added ( ( @rocallahan @khuey ) ? It would depend of course on how these XML files now in `rr` sources were obtained/generated. 

```
<!-- Copyright (C) 2014-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->
```

2025-03-17 14:31 UTC, khuey commented
Yes if these were copied from the gdb repo they need the copyright headers.

2025-03-17 15:09 UTC, theIDinside commented
> Yes if these were copied from the gdb repo they need the copyright headers.

This had somehow slipped through my fingers. Addressed in https://github.com/rr-debugger/rr/pull/3934